enum Tier {
  UNRANK = "UNRANK",
  IRON = "IRON",
  BRONZE = "BRONZE",
  SILVER = "SILVER",
  GOLD = "GOLD",
  PLATINUM = "PLATINUM",
  EMERALD = "EMERALD",
  DIAMOND = "DIAMOND",
  MASTER = "MASTER",
  GRANDMASTER = "GRANDMASTER",
  CHALLENGER = "CHALLENGER",
}

export default Tier;
